"""add column of request time

Revision ID: 895087f621ae
Revises: 5c81373a90cb
Create Date: 2025-07-29 16:16:15.487156

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '895087f621ae'
down_revision: Union[str, Sequence[str], None] = '5c81373a90cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('requests', sa.Column('time_of_request', sa.TIMESTAMP(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('requests', 'time_of_request')
    # ### end Alembic commands ###
